services:

  # Container do banco de dados PostgreSQL
  db:
    image: postgres:16
    env_file: .env    # le as variaveis do arquivo .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"  # porta-do-seu-pc:porta-dentro-do-container
    volumes:
      - pgdata:/var/lib/postgresql/data  # persiste os dados mesmo ao reiniciar
    networks:
      - arenapro-net

  # Container do servico principal (Java + Quarkus)
  api:
    build:
      context: ./api
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_DATASOURCE_JDBC_URL: ${DATABASE_URL}
      QUARKUS_DATASOURCE_USERNAME: ${DATABASE_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db          # banco sobe antes da API
      - notificacao
    networks:
      - arenapro-net

  # Container do servico de notificacoes (Go)
  notificacao:
    build:
      context: ./services/notificacao
    ports:
      - "8081:8081"
    networks:
      - arenapro-net

# Volume nomeado para persistir os dados do banco
volumes:
  pgdata:

# Rede interna criada pelo Docker para os containers se comunicarem
networks:
  arenapro-net:
    driver: bridge