# Le de variavel de ambiente, com valor padrao para desenvolvimento
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DATABASE_USER:postgres}
quarkus.datasource.password=${DATABASE_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/palpitearena}

quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.schema-management.strategy=none